# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rl_service_pb2 as rl__service__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rl_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RLServiceStub(object):
    """gRPC service for RL agent action selection
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SelectAction = channel.unary_unary(
                '/rl_service.RLService/SelectAction',
                request_serializer=rl__service__pb2.ActionRequest.SerializeToString,
                response_deserializer=rl__service__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.SelectActionStream = channel.stream_stream(
                '/rl_service.RLService/SelectActionStream',
                request_serializer=rl__service__pb2.ActionRequest.SerializeToString,
                response_deserializer=rl__service__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ResetAgent = channel.unary_unary(
                '/rl_service.RLService/ResetAgent',
                request_serializer=rl__service__pb2.ResetRequest.SerializeToString,
                response_deserializer=rl__service__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.SaveModel = channel.unary_unary(
                '/rl_service.RLService/SaveModel',
                request_serializer=rl__service__pb2.SaveRequest.SerializeToString,
                response_deserializer=rl__service__pb2.SaveResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/rl_service.RLService/LoadModel',
                request_serializer=rl__service__pb2.LoadRequest.SerializeToString,
                response_deserializer=rl__service__pb2.LoadResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/rl_service.RLService/GetStats',
                request_serializer=rl__service__pb2.StatsRequest.SerializeToString,
                response_deserializer=rl__service__pb2.StatsResponse.FromString,
                _registered_method=True)


class RLServiceServicer(object):
    """gRPC service for RL agent action selection
    """

    def SelectAction(self, request, context):
        """Single action selection (blocking)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelectActionStream(self, request_iterator, context):
        """Bidirectional streaming for maximum throughput (future optimization)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetAgent(self, request, context):
        """Agent management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SelectAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SelectAction,
                    request_deserializer=rl__service__pb2.ActionRequest.FromString,
                    response_serializer=rl__service__pb2.ActionResponse.SerializeToString,
            ),
            'SelectActionStream': grpc.stream_stream_rpc_method_handler(
                    servicer.SelectActionStream,
                    request_deserializer=rl__service__pb2.ActionRequest.FromString,
                    response_serializer=rl__service__pb2.ActionResponse.SerializeToString,
            ),
            'ResetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetAgent,
                    request_deserializer=rl__service__pb2.ResetRequest.FromString,
                    response_serializer=rl__service__pb2.ResetResponse.SerializeToString,
            ),
            'SaveModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveModel,
                    request_deserializer=rl__service__pb2.SaveRequest.FromString,
                    response_serializer=rl__service__pb2.SaveResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=rl__service__pb2.LoadRequest.FromString,
                    response_serializer=rl__service__pb2.LoadResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=rl__service__pb2.StatsRequest.FromString,
                    response_serializer=rl__service__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rl_service.RLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rl_service.RLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RLService(object):
    """gRPC service for RL agent action selection
    """

    @staticmethod
    def SelectAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_service.RLService/SelectAction',
            rl__service__pb2.ActionRequest.SerializeToString,
            rl__service__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SelectActionStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/rl_service.RLService/SelectActionStream',
            rl__service__pb2.ActionRequest.SerializeToString,
            rl__service__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_service.RLService/ResetAgent',
            rl__service__pb2.ResetRequest.SerializeToString,
            rl__service__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_service.RLService/SaveModel',
            rl__service__pb2.SaveRequest.SerializeToString,
            rl__service__pb2.SaveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_service.RLService/LoadModel',
            rl__service__pb2.LoadRequest.SerializeToString,
            rl__service__pb2.LoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rl_service.RLService/GetStats',
            rl__service__pb2.StatsRequest.SerializeToString,
            rl__service__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
